### ISSUE TITLE
CUDA out of memory.   Could you tell me your GPU configuration?

### ISSUE THREAD

**Issue by Reckless564** [ShiZiqiang/dual-path-RNNs-DPRNNs-based-speech-separation#1]
In the training stage of train_data, it runs well. However, for the valid_data, it occurs the ERROR "out of memory".  I used 2 RTX 2080 TI and I have setted the batch_size to 1. 

Looking forward to your reply, thanks!

**Comment by ShiZiqiang** [comment]
Hi, Reckless. We have test the training process succefully indepently both on a TITAN RTX and a TITAN XP.

**Comment by JunzheJosephZhu** [comment]
How long did it take for you to train this?

**Comment by ShiZiqiang** [comment]
Hi, Joseph. It took me about 7-10 days to train a satisfied model.
